@echo Activating Emscripten...
@call D:/Emscripten/emsdk/emsdk_env.bat
@echo Compiling...
@call emcc -O3 dewarp.c -o dewarp.js --post-js dewarp_post.js -s ENVIRONMENT="web" -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1
@echo Done!